package com.quizmael.gui.views.profile;

import com.quizmael.gui.views.auth.*;

/**
 * TODO: generar descripción
 * 
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class AppSettings extends com.quizmael.gui.common.BasePanel {
    
    // ------------------------------------------------------------
    //                     Attributes
    // ------------------------------------------------------------

    
    // ------------------------------------------------------------
    //                     Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form LoginPanel
     */
    public AppSettings() {
        initComponents();
    }
    
    
    // ------------------------------------------------------------
    //                     Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        northPanel = new javax.swing.JPanel();
        lblLanguage = new javax.swing.JLabel();
        cboLanguage = new javax.swing.JComboBox<>();
        btnUserSettings = new javax.swing.JButton();
        lblAppTheme = new javax.swing.JLabel();
        cboAppTheme = new javax.swing.JComboBox<>();
        lblVolume = new javax.swing.JLabel();
        sldVolume = new javax.swing.JSlider();
        tbtMuteApp = new javax.swing.JToggleButton();
        southPanel = new javax.swing.JPanel();
        btnUserManual = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 100, 50, 100));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        northPanel.setLayout(new java.awt.GridBagLayout());

        lblLanguage.setMaximumSize(new java.awt.Dimension(300, 50));
        lblLanguage.setMinimumSize(new java.awt.Dimension(50, 30));
        lblLanguage.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        northPanel.add(lblLanguage, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        northPanel.add(cboLanguage, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        northPanel.add(btnUserSettings, gridBagConstraints);

        lblAppTheme.setMaximumSize(new java.awt.Dimension(300, 50));
        lblAppTheme.setMinimumSize(new java.awt.Dimension(50, 30));
        lblAppTheme.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        northPanel.add(lblAppTheme, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        northPanel.add(cboAppTheme, gridBagConstraints);

        lblVolume.setMaximumSize(new java.awt.Dimension(300, 50));
        lblVolume.setMinimumSize(new java.awt.Dimension(50, 30));
        lblVolume.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        northPanel.add(lblVolume, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        northPanel.add(sldVolume, gridBagConstraints);

        tbtMuteApp.setText("jToggleButton1");
        tbtMuteApp.setMaximumSize(new java.awt.Dimension(75, 75));
        tbtMuteApp.setMinimumSize(new java.awt.Dimension(75, 75));
        tbtMuteApp.setPreferredSize(new java.awt.Dimension(75, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        northPanel.add(tbtMuteApp, gridBagConstraints);

        add(northPanel, java.awt.BorderLayout.NORTH);

        southPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        btnUserManual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnUserManual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUserManual.setMaximumSize(new java.awt.Dimension(250, 150));
        btnUserManual.setMinimumSize(new java.awt.Dimension(150, 100));
        btnUserManual.setPreferredSize(new java.awt.Dimension(150, 100));
        btnUserManual.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        southPanel.add(btnUserManual);

        add(southPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserManual;
    private javax.swing.JButton btnUserSettings;
    private javax.swing.JComboBox<String> cboAppTheme;
    private javax.swing.JComboBox<String> cboLanguage;
    private javax.swing.JLabel lblAppTheme;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JPanel northPanel;
    private javax.swing.JSlider sldVolume;
    private javax.swing.JPanel southPanel;
    private javax.swing.JToggleButton tbtMuteApp;
    // End of variables declaration//GEN-END:variables
}
