package com.quizmael.gui.views.game;

import com.quizmael.gui.views.profile.*;
import com.quizmael.gui.views.auth.*;

/**
 * TODO: generar descripción
 * 
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class PlayPanel extends com.quizmael.gui.common.BasePanel {
    
    // ------------------------------------------------------------
    //                     Attributes
    // ------------------------------------------------------------

    
    // ------------------------------------------------------------
    //                     Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form LoginPanel
     */
    public PlayPanel() {
        initComponents();
    }
    
    
    // ------------------------------------------------------------
    //                     Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        northPanel = new javax.swing.JPanel();
        lblQuestion = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        tbtAnswer1 = new javax.swing.JToggleButton();
        tbtAnswer2 = new javax.swing.JToggleButton();
        tbtAnswer3 = new javax.swing.JToggleButton();
        tbtAnswer4 = new javax.swing.JToggleButton();
        southPanel = new javax.swing.JPanel();
        feedBackPanel = new javax.swing.JPanel();
        lblQuestion1 = new javax.swing.JLabel();
        StartGamePanel = new javax.swing.JPanel();
        verticalGlue = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAnswer = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 100, 50, 100));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        northPanel.setMinimumSize(new java.awt.Dimension(600, 120));
        northPanel.setPreferredSize(new java.awt.Dimension(600, 120));
        northPanel.setLayout(new java.awt.GridBagLayout());

        lblQuestion.setMaximumSize(new java.awt.Dimension(300, 50));
        lblQuestion.setMinimumSize(new java.awt.Dimension(50, 30));
        lblQuestion.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        northPanel.add(lblQuestion, gridBagConstraints);

        lblTime.setMaximumSize(new java.awt.Dimension(300, 50));
        lblTime.setMinimumSize(new java.awt.Dimension(50, 30));
        lblTime.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        northPanel.add(lblTime, gridBagConstraints);

        add(northPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 15, 0));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        buttonGroup.add(tbtAnswer1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        centerPanel.add(tbtAnswer1, gridBagConstraints);

        buttonGroup.add(tbtAnswer2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        centerPanel.add(tbtAnswer2, gridBagConstraints);

        buttonGroup.add(tbtAnswer3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        centerPanel.add(tbtAnswer3, gridBagConstraints);

        buttonGroup.add(tbtAnswer4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        centerPanel.add(tbtAnswer4, gridBagConstraints);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        southPanel.setMinimumSize(new java.awt.Dimension(600, 120));
        southPanel.setPreferredSize(new java.awt.Dimension(600, 120));
        southPanel.setLayout(new java.awt.BorderLayout());

        feedBackPanel.setMinimumSize(new java.awt.Dimension(800, 50));
        feedBackPanel.setPreferredSize(new java.awt.Dimension(800, 100));
        feedBackPanel.setLayout(new java.awt.GridBagLayout());

        lblQuestion1.setMaximumSize(new java.awt.Dimension(300, 50));
        lblQuestion1.setMinimumSize(new java.awt.Dimension(50, 30));
        lblQuestion1.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        feedBackPanel.add(lblQuestion1, gridBagConstraints);

        southPanel.add(feedBackPanel, java.awt.BorderLayout.WEST);

        StartGamePanel.setMinimumSize(new java.awt.Dimension(190, 60));
        StartGamePanel.setPreferredSize(new java.awt.Dimension(190, 60));
        StartGamePanel.setLayout(new javax.swing.BoxLayout(StartGamePanel, javax.swing.BoxLayout.Y_AXIS));
        StartGamePanel.add(verticalGlue);

        btnAnswer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAnswer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnswer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAnswer.setMaximumSize(new java.awt.Dimension(250, 150));
        btnAnswer.setMinimumSize(new java.awt.Dimension(190, 60));
        btnAnswer.setPreferredSize(new java.awt.Dimension(190, 60));
        btnAnswer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        StartGamePanel.add(btnAnswer);

        southPanel.add(StartGamePanel, java.awt.BorderLayout.EAST);

        add(southPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StartGamePanel;
    private javax.swing.JButton btnAnswer;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel feedBackPanel;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel southPanel;
    private javax.swing.JToggleButton tbtAnswer1;
    private javax.swing.JToggleButton tbtAnswer2;
    private javax.swing.JToggleButton tbtAnswer3;
    private javax.swing.JToggleButton tbtAnswer4;
    private javax.swing.Box.Filler verticalGlue;
    // End of variables declaration//GEN-END:variables
}
