package com.quizmael.gui.views.game;

import com.quizmael.controller.AppController;
import com.quizmael.gui.views.profile.*;
import com.quizmael.gui.views.auth.*;

/**
 * Panel for browsing and selecting available quizzes.
 * Allows users to filter or choose a quiz to play.
 * 
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class QuizSelectionPanel extends com.quizmael.gui.common.BasePanel {
    
    // ------------------------------------------------------------
    //                     Attributes
    // ------------------------------------------------------------

    
    // ------------------------------------------------------------
    //                     Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form LoginPanel
     */
    public QuizSelectionPanel(AppController controller) {
        initComponents();
    }
    
    
    // ------------------------------------------------------------
    //                     Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        northPanel = new javax.swing.JPanel();
        tabbedPanel = new javax.swing.JTabbedPane();
        centerPanel = new javax.swing.JPanel();
        cboLanguage = new javax.swing.JComboBox<>();
        cboAppTheme = new javax.swing.JComboBox<>();
        lblVolume = new javax.swing.JLabel();
        sldVolume = new javax.swing.JSlider();
        scpTableQujzzes = new javax.swing.JScrollPane();
        tableQuizzes = new javax.swing.JTable();
        quizConfigurationPanel = new javax.swing.JPanel();
        lblVolume1 = new javax.swing.JLabel();
        cboLanguage1 = new javax.swing.JComboBox<>();
        lblVolume2 = new javax.swing.JLabel();
        cboLanguage2 = new javax.swing.JComboBox<>();
        lblVolume3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        southPanel = new javax.swing.JPanel();
        quizDetailsPanel = new javax.swing.JPanel();
        imgSelectedQuizPanel = new javax.swing.JPanel();
        lblSelectedQuizImage = new javax.swing.JLabel();
        infoSelectedQuizPanel = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblUserName1 = new javax.swing.JLabel();
        lblUserName2 = new javax.swing.JLabel();
        lblUserName3 = new javax.swing.JLabel();
        lblUserName4 = new javax.swing.JLabel();
        lblUserName5 = new javax.swing.JLabel();
        lblUserName6 = new javax.swing.JLabel();
        lblUserName7 = new javax.swing.JLabel();
        lblUserName8 = new javax.swing.JLabel();
        lblUserName9 = new javax.swing.JLabel();
        lblUserName10 = new javax.swing.JLabel();
        lblUserName11 = new javax.swing.JLabel();
        startGamePanel = new javax.swing.JPanel();
        verticalGlue = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnUserManual = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 100, 50, 100));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        northPanel.setLayout(new java.awt.GridBagLayout());

        tabbedPanel.setMinimumSize(new java.awt.Dimension(900, 180));
        tabbedPanel.setPreferredSize(new java.awt.Dimension(900, 180));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        northPanel.add(tabbedPanel, gridBagConstraints);

        add(northPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 15, 0));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        centerPanel.add(cboLanguage, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        centerPanel.add(cboAppTheme, gridBagConstraints);

        lblVolume.setMaximumSize(new java.awt.Dimension(300, 50));
        lblVolume.setMinimumSize(new java.awt.Dimension(50, 30));
        lblVolume.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        centerPanel.add(lblVolume, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        centerPanel.add(sldVolume, gridBagConstraints);

        scpTableQujzzes.setMinimumSize(new java.awt.Dimension(1000, 150));
        scpTableQujzzes.setPreferredSize(new java.awt.Dimension(1000, 150));

        tableQuizzes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        scpTableQujzzes.setViewportView(tableQuizzes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        centerPanel.add(scpTableQujzzes, gridBagConstraints);

        quizConfigurationPanel.setLayout(new java.awt.GridBagLayout());

        lblVolume1.setMaximumSize(new java.awt.Dimension(300, 50));
        lblVolume1.setMinimumSize(new java.awt.Dimension(50, 30));
        lblVolume1.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        quizConfigurationPanel.add(lblVolume1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        quizConfigurationPanel.add(cboLanguage1, gridBagConstraints);

        lblVolume2.setMaximumSize(new java.awt.Dimension(300, 50));
        lblVolume2.setMinimumSize(new java.awt.Dimension(50, 30));
        lblVolume2.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        quizConfigurationPanel.add(lblVolume2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        quizConfigurationPanel.add(cboLanguage2, gridBagConstraints);

        lblVolume3.setMaximumSize(new java.awt.Dimension(300, 50));
        lblVolume3.setMinimumSize(new java.awt.Dimension(50, 30));
        lblVolume3.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        quizConfigurationPanel.add(lblVolume3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        quizConfigurationPanel.add(jTextField1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        centerPanel.add(quizConfigurationPanel, gridBagConstraints);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        southPanel.setLayout(new java.awt.BorderLayout());

        quizDetailsPanel.setMinimumSize(new java.awt.Dimension(800, 50));
        quizDetailsPanel.setPreferredSize(new java.awt.Dimension(800, 100));
        quizDetailsPanel.setLayout(new java.awt.BorderLayout());

        lblSelectedQuizImage.setMaximumSize(new java.awt.Dimension(150, 150));
        lblSelectedQuizImage.setMinimumSize(new java.awt.Dimension(100, 100));
        lblSelectedQuizImage.setPreferredSize(new java.awt.Dimension(100, 100));
        imgSelectedQuizPanel.add(lblSelectedQuizImage);

        quizDetailsPanel.add(imgSelectedQuizPanel, java.awt.BorderLayout.WEST);

        infoSelectedQuizPanel.setLayout(new java.awt.GridBagLayout());

        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName, gridBagConstraints);

        lblUserName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName1.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName1.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName1.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName1, gridBagConstraints);

        lblUserName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName2.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName2.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName2.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName2, gridBagConstraints);

        lblUserName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName3.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName3.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName3.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName3, gridBagConstraints);

        lblUserName4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName4.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName4.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName4.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName4, gridBagConstraints);

        lblUserName5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName5.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName5.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName5.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName5, gridBagConstraints);

        lblUserName6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName6.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName6.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName6.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName6, gridBagConstraints);

        lblUserName7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName7.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName7.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName7.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName7, gridBagConstraints);

        lblUserName8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName8.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName8.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName8.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName8, gridBagConstraints);

        lblUserName9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName9.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName9.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName9.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName9, gridBagConstraints);

        lblUserName10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName10.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName10.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName10.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName10, gridBagConstraints);

        lblUserName11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName11.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName11.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName11.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        infoSelectedQuizPanel.add(lblUserName11, gridBagConstraints);

        quizDetailsPanel.add(infoSelectedQuizPanel, java.awt.BorderLayout.CENTER);

        southPanel.add(quizDetailsPanel, java.awt.BorderLayout.WEST);

        startGamePanel.setMinimumSize(new java.awt.Dimension(190, 60));
        startGamePanel.setPreferredSize(new java.awt.Dimension(190, 60));
        startGamePanel.setLayout(new javax.swing.BoxLayout(startGamePanel, javax.swing.BoxLayout.Y_AXIS));
        startGamePanel.add(verticalGlue);

        btnUserManual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnUserManual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUserManual.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUserManual.setMaximumSize(new java.awt.Dimension(250, 150));
        btnUserManual.setMinimumSize(new java.awt.Dimension(190, 60));
        btnUserManual.setPreferredSize(new java.awt.Dimension(190, 60));
        btnUserManual.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        startGamePanel.add(btnUserManual);

        southPanel.add(startGamePanel, java.awt.BorderLayout.EAST);

        add(southPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserManual;
    private javax.swing.JComboBox<String> cboAppTheme;
    private javax.swing.JComboBox<String> cboLanguage;
    private javax.swing.JComboBox<String> cboLanguage1;
    private javax.swing.JComboBox<String> cboLanguage2;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel imgSelectedQuizPanel;
    private javax.swing.JPanel infoSelectedQuizPanel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblSelectedQuizImage;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JLabel lblUserName10;
    private javax.swing.JLabel lblUserName11;
    private javax.swing.JLabel lblUserName2;
    private javax.swing.JLabel lblUserName3;
    private javax.swing.JLabel lblUserName4;
    private javax.swing.JLabel lblUserName5;
    private javax.swing.JLabel lblUserName6;
    private javax.swing.JLabel lblUserName7;
    private javax.swing.JLabel lblUserName8;
    private javax.swing.JLabel lblUserName9;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JLabel lblVolume1;
    private javax.swing.JLabel lblVolume2;
    private javax.swing.JLabel lblVolume3;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel quizConfigurationPanel;
    private javax.swing.JPanel quizDetailsPanel;
    private javax.swing.JScrollPane scpTableQujzzes;
    private javax.swing.JSlider sldVolume;
    private javax.swing.JPanel southPanel;
    private javax.swing.JPanel startGamePanel;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTable tableQuizzes;
    private javax.swing.Box.Filler verticalGlue;
    // End of variables declaration//GEN-END:variables
}
