package com.quizmael.gui.views.game;

import com.quizmael.controller.AppController;
import com.quizmael.gui.views.profile.*;
import com.quizmael.gui.views.auth.*;

/**
 * Panel to show quiz results after completion.
 * Displays score, correct/incorrect answers, and statistics.
 * 
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class ResultsPanel extends com.quizmael.gui.common.BasePanel {
    
    // ------------------------------------------------------------
    //                     Attributes
    // ------------------------------------------------------------

    
    // ------------------------------------------------------------
    //                     Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form LoginPanel
     */
    public ResultsPanel(AppController controller) {
        initComponents();
    }
    
    
    // ------------------------------------------------------------
    //                     Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        northPanel = new javax.swing.JPanel();
        lblQuestion = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        answersPanel = new javax.swing.JPanel();
        lblWrong = new javax.swing.JLabel();
        lblWrongNumber = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblCorrectNumber = new javax.swing.JLabel();
        scorePanel = new javax.swing.JPanel();
        lblScore = new javax.swing.JLabel();
        lblScoreNumber = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        feedBackPanel = new javax.swing.JPanel();
        verticalGlue1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAnswer1 = new javax.swing.JButton();
        StartGamePanel = new javax.swing.JPanel();
        verticalGlue = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAnswer = new javax.swing.JButton();
        addFavoritePanel = new javax.swing.JPanel();
        verticalGlue2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAddFavorite = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 100, 50, 100));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        northPanel.setMinimumSize(new java.awt.Dimension(600, 120));
        northPanel.setPreferredSize(new java.awt.Dimension(600, 120));
        northPanel.setLayout(new java.awt.GridBagLayout());

        lblQuestion.setMaximumSize(new java.awt.Dimension(300, 50));
        lblQuestion.setMinimumSize(new java.awt.Dimension(50, 30));
        lblQuestion.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        northPanel.add(lblQuestion, gridBagConstraints);

        add(northPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 15, 0));
        centerPanel.setLayout(new java.awt.BorderLayout());

        answersPanel.setMinimumSize(new java.awt.Dimension(300, 60));
        answersPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        answersPanel.setLayout(new java.awt.GridBagLayout());

        lblWrong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWrong.setMaximumSize(new java.awt.Dimension(300, 50));
        lblWrong.setMinimumSize(new java.awt.Dimension(100, 50));
        lblWrong.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        answersPanel.add(lblWrong, gridBagConstraints);

        lblWrongNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWrongNumber.setMaximumSize(new java.awt.Dimension(300, 50));
        lblWrongNumber.setMinimumSize(new java.awt.Dimension(100, 50));
        lblWrongNumber.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        answersPanel.add(lblWrongNumber, gridBagConstraints);

        lblCorrect.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCorrect.setMaximumSize(new java.awt.Dimension(300, 50));
        lblCorrect.setMinimumSize(new java.awt.Dimension(100, 50));
        lblCorrect.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        answersPanel.add(lblCorrect, gridBagConstraints);

        lblCorrectNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCorrectNumber.setMaximumSize(new java.awt.Dimension(300, 50));
        lblCorrectNumber.setMinimumSize(new java.awt.Dimension(100, 50));
        lblCorrectNumber.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        answersPanel.add(lblCorrectNumber, gridBagConstraints);

        centerPanel.add(answersPanel, java.awt.BorderLayout.WEST);

        scorePanel.setMinimumSize(new java.awt.Dimension(200, 200));
        scorePanel.setPreferredSize(new java.awt.Dimension(200, 200));
        scorePanel.setLayout(new javax.swing.BoxLayout(scorePanel, javax.swing.BoxLayout.Y_AXIS));

        lblScore.setMaximumSize(new java.awt.Dimension(300, 50));
        lblScore.setMinimumSize(new java.awt.Dimension(150, 30));
        lblScore.setPreferredSize(new java.awt.Dimension(150, 30));
        scorePanel.add(lblScore);

        lblScoreNumber.setMaximumSize(new java.awt.Dimension(300, 150));
        lblScoreNumber.setMinimumSize(new java.awt.Dimension(150, 80));
        lblScoreNumber.setPreferredSize(new java.awt.Dimension(150, 80));
        scorePanel.add(lblScoreNumber);

        centerPanel.add(scorePanel, java.awt.BorderLayout.EAST);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        southPanel.setMinimumSize(new java.awt.Dimension(600, 120));
        southPanel.setPreferredSize(new java.awt.Dimension(600, 150));
        southPanel.setLayout(new java.awt.BorderLayout());

        feedBackPanel.setMinimumSize(new java.awt.Dimension(140, 100));
        feedBackPanel.setPreferredSize(new java.awt.Dimension(140, 100));
        feedBackPanel.setLayout(new javax.swing.BoxLayout(feedBackPanel, javax.swing.BoxLayout.Y_AXIS));
        feedBackPanel.add(verticalGlue1);

        btnAnswer1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAnswer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnswer1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAnswer1.setMaximumSize(new java.awt.Dimension(250, 150));
        btnAnswer1.setMinimumSize(new java.awt.Dimension(140, 100));
        btnAnswer1.setPreferredSize(new java.awt.Dimension(140, 100));
        btnAnswer1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        feedBackPanel.add(btnAnswer1);

        southPanel.add(feedBackPanel, java.awt.BorderLayout.WEST);

        StartGamePanel.setMinimumSize(new java.awt.Dimension(210, 70));
        StartGamePanel.setPreferredSize(new java.awt.Dimension(210, 70));
        StartGamePanel.setLayout(new javax.swing.BoxLayout(StartGamePanel, javax.swing.BoxLayout.Y_AXIS));
        StartGamePanel.add(verticalGlue);

        btnAnswer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAnswer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnswer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAnswer.setMaximumSize(new java.awt.Dimension(250, 150));
        btnAnswer.setMinimumSize(new java.awt.Dimension(190, 70));
        btnAnswer.setPreferredSize(new java.awt.Dimension(190, 70));
        btnAnswer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        StartGamePanel.add(btnAnswer);

        southPanel.add(StartGamePanel, java.awt.BorderLayout.EAST);

        addFavoritePanel.setLayout(new javax.swing.BoxLayout(addFavoritePanel, javax.swing.BoxLayout.Y_AXIS));
        addFavoritePanel.add(verticalGlue2);

        btnAddFavorite.setAlignmentX(0.5F);
        btnAddFavorite.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddFavorite.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAddFavorite.setMaximumSize(new java.awt.Dimension(170, 150));
        btnAddFavorite.setMinimumSize(new java.awt.Dimension(140, 55));
        btnAddFavorite.setPreferredSize(new java.awt.Dimension(140, 55));
        btnAddFavorite.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addFavoritePanel.add(btnAddFavorite);

        southPanel.add(addFavoritePanel, java.awt.BorderLayout.CENTER);

        add(southPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StartGamePanel;
    private javax.swing.JPanel addFavoritePanel;
    private javax.swing.JPanel answersPanel;
    private javax.swing.JButton btnAddFavorite;
    private javax.swing.JButton btnAnswer;
    private javax.swing.JButton btnAnswer1;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel feedBackPanel;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectNumber;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreNumber;
    private javax.swing.JLabel lblWrong;
    private javax.swing.JLabel lblWrongNumber;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JPanel southPanel;
    private javax.swing.Box.Filler verticalGlue;
    private javax.swing.Box.Filler verticalGlue1;
    private javax.swing.Box.Filler verticalGlue2;
    // End of variables declaration//GEN-END:variables
}
