package com.quizmael.gui.views.admin;

import com.quizmael.controller.AppController;
import com.quizmael.gui.common.*;
import com.quizmael.gui.views.auth.*;

/**
 * Administrative panel for managing users, content, and system configurations.
 * Only accessible to users with administrator privileges.
 * 
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class AdminPanel extends com.quizmael.gui.common.BasePanel {
    
    // ------------------------------------------------------------
    //                     Attributes
    // ------------------------------------------------------------

    
    // ------------------------------------------------------------
    //                     Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form LoginPanel
     */
    public AdminPanel(AppController controller) {
        initComponents();
    }
    
    
    // ------------------------------------------------------------
    //                     Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        westPanel = new javax.swing.JPanel();
        filtersPanel = new javax.swing.JPanel();
        lblFiltersTitle = new javax.swing.JLabel();
        lblFilterRole = new javax.swing.JLabel();
        cboFilterRole = new javax.swing.JComboBox<>();
        lblFilterName = new javax.swing.JLabel();
        txtFilterName = new javax.swing.JTextField();
        lblFilterEmail = new javax.swing.JLabel();
        txtFilterEmail = new javax.swing.JTextField();
        backButtonPanel = new javax.swing.JPanel();
        btnAnswer1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        centerPanel = new javax.swing.JPanel();
        searchResultsPanel = new javax.swing.JPanel();
        lblResultsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editPanel = new javax.swing.JPanel();
        lblEditTitle = new javax.swing.JLabel();
        lblEditId = new javax.swing.JLabel();
        txtEditId = new javax.swing.JTextField();
        lblEditName = new javax.swing.JLabel();
        txtEditName = new javax.swing.JTextField();
        lblEditRole = new javax.swing.JLabel();
        cboEditRole = new javax.swing.JComboBox<>();
        lblEditEmail = new javax.swing.JLabel();
        txtEditEmail = new javax.swing.JTextField();
        lblEditBirthDate = new javax.swing.JLabel();
        txtEditBirthDate = new javax.swing.JTextField();
        lblEditPassword = new javax.swing.JLabel();
        txtEditPassword = new javax.swing.JTextField();
        lblEditPasswordHint = new javax.swing.JLabel();
        txtEditPasswordHint = new javax.swing.JTextField();
        lblEditSecretQuestion = new javax.swing.JLabel();
        txtEditSecretQuestion = new javax.swing.JTextField();
        lblEditSecretAnswer = new javax.swing.JLabel();
        txtEditSecretAnswer = new javax.swing.JTextField();
        lblEditImage = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.BorderLayout());

        westPanel.setLayout(new java.awt.BorderLayout());

        filtersPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 20)));
        filtersPanel.setMinimumSize(new java.awt.Dimension(250, 45));
        filtersPanel.setPreferredSize(new java.awt.Dimension(250, 600));
        filtersPanel.setLayout(new java.awt.GridBagLayout());

        lblFiltersTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFiltersTitle.setMaximumSize(new java.awt.Dimension(300, 50));
        lblFiltersTitle.setMinimumSize(new java.awt.Dimension(100, 50));
        lblFiltersTitle.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        filtersPanel.add(lblFiltersTitle, gridBagConstraints);

        lblFilterRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFilterRole.setMaximumSize(new java.awt.Dimension(300, 50));
        lblFilterRole.setMinimumSize(new java.awt.Dimension(100, 25));
        lblFilterRole.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        filtersPanel.add(lblFilterRole, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        filtersPanel.add(cboFilterRole, gridBagConstraints);

        lblFilterName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFilterName.setMaximumSize(new java.awt.Dimension(300, 50));
        lblFilterName.setMinimumSize(new java.awt.Dimension(100, 25));
        lblFilterName.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        filtersPanel.add(lblFilterName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        filtersPanel.add(txtFilterName, gridBagConstraints);

        lblFilterEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFilterEmail.setMaximumSize(new java.awt.Dimension(300, 50));
        lblFilterEmail.setMinimumSize(new java.awt.Dimension(100, 25));
        lblFilterEmail.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        filtersPanel.add(lblFilterEmail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        filtersPanel.add(txtFilterEmail, gridBagConstraints);

        westPanel.add(filtersPanel, java.awt.BorderLayout.CENTER);

        backButtonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 20));
        backButtonPanel.setLayout(new javax.swing.BoxLayout(backButtonPanel, javax.swing.BoxLayout.LINE_AXIS));

        btnAnswer1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAnswer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnswer1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAnswer1.setMaximumSize(new java.awt.Dimension(250, 150));
        btnAnswer1.setMinimumSize(new java.awt.Dimension(140, 100));
        btnAnswer1.setPreferredSize(new java.awt.Dimension(140, 100));
        btnAnswer1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        backButtonPanel.add(btnAnswer1);
        backButtonPanel.add(filler1);

        westPanel.add(backButtonPanel, java.awt.BorderLayout.SOUTH);

        add(westPanel, java.awt.BorderLayout.LINE_START);

        centerPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        centerPanel.setName(""); // NOI18N
        centerPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        centerPanel.setLayout(new java.awt.BorderLayout());

        searchResultsPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(8, 20, 8, 8)));
        searchResultsPanel.setMinimumSize(new java.awt.Dimension(800, 360));
        searchResultsPanel.setPreferredSize(new java.awt.Dimension(800, 360));
        searchResultsPanel.setLayout(new java.awt.GridBagLayout());

        lblResultsTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResultsTitle.setMaximumSize(new java.awt.Dimension(300, 50));
        lblResultsTitle.setMinimumSize(new java.awt.Dimension(100, 50));
        lblResultsTitle.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        searchResultsPanel.add(lblResultsTitle, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 280));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(453, 280));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        searchResultsPanel.add(jScrollPane1, gridBagConstraints);

        centerPanel.add(searchResultsPanel, java.awt.BorderLayout.NORTH);

        editPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(8, 20, 8, 8)));
        editPanel.setMinimumSize(new java.awt.Dimension(800, 360));
        editPanel.setPreferredSize(new java.awt.Dimension(800, 360));
        editPanel.setLayout(new java.awt.GridBagLayout());

        lblEditTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditTitle.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditTitle.setMinimumSize(new java.awt.Dimension(100, 50));
        lblEditTitle.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editPanel.add(lblEditTitle, gridBagConstraints);

        lblEditId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditId.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblEditId.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditId.setMinimumSize(new java.awt.Dimension(100, 25));
        lblEditId.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(lblEditId, gridBagConstraints);

        txtEditId.setMinimumSize(new java.awt.Dimension(100, 25));
        txtEditId.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(txtEditId, gridBagConstraints);

        lblEditName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblEditName.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditName.setMinimumSize(new java.awt.Dimension(100, 25));
        lblEditName.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(lblEditName, gridBagConstraints);

        txtEditName.setMinimumSize(new java.awt.Dimension(100, 25));
        txtEditName.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(txtEditName, gridBagConstraints);

        lblEditRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditRole.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblEditRole.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditRole.setMinimumSize(new java.awt.Dimension(100, 25));
        lblEditRole.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(lblEditRole, gridBagConstraints);

        cboEditRole.setMinimumSize(new java.awt.Dimension(100, 25));
        cboEditRole.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(cboEditRole, gridBagConstraints);

        lblEditEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditEmail.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditEmail.setMinimumSize(new java.awt.Dimension(100, 25));
        lblEditEmail.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(lblEditEmail, gridBagConstraints);

        txtEditEmail.setMinimumSize(new java.awt.Dimension(100, 25));
        txtEditEmail.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(txtEditEmail, gridBagConstraints);

        lblEditBirthDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditBirthDate.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditBirthDate.setMinimumSize(new java.awt.Dimension(100, 25));
        lblEditBirthDate.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(lblEditBirthDate, gridBagConstraints);

        txtEditBirthDate.setMinimumSize(new java.awt.Dimension(100, 25));
        txtEditBirthDate.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(txtEditBirthDate, gridBagConstraints);

        lblEditPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditPassword.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditPassword.setMinimumSize(new java.awt.Dimension(100, 25));
        lblEditPassword.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(lblEditPassword, gridBagConstraints);

        txtEditPassword.setMinimumSize(new java.awt.Dimension(100, 25));
        txtEditPassword.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(txtEditPassword, gridBagConstraints);

        lblEditPasswordHint.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditPasswordHint.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditPasswordHint.setMinimumSize(new java.awt.Dimension(100, 25));
        lblEditPasswordHint.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(lblEditPasswordHint, gridBagConstraints);

        txtEditPasswordHint.setMinimumSize(new java.awt.Dimension(100, 25));
        txtEditPasswordHint.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(txtEditPasswordHint, gridBagConstraints);

        lblEditSecretQuestion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditSecretQuestion.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditSecretQuestion.setMinimumSize(new java.awt.Dimension(100, 25));
        lblEditSecretQuestion.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(lblEditSecretQuestion, gridBagConstraints);

        txtEditSecretQuestion.setMinimumSize(new java.awt.Dimension(100, 25));
        txtEditSecretQuestion.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(txtEditSecretQuestion, gridBagConstraints);

        lblEditSecretAnswer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditSecretAnswer.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEditSecretAnswer.setMinimumSize(new java.awt.Dimension(100, 25));
        lblEditSecretAnswer.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(lblEditSecretAnswer, gridBagConstraints);

        txtEditSecretAnswer.setMinimumSize(new java.awt.Dimension(100, 25));
        txtEditSecretAnswer.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        editPanel.add(txtEditSecretAnswer, gridBagConstraints);

        lblEditImage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditImage.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));
        lblEditImage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblEditImage.setMaximumSize(new java.awt.Dimension(300, 200));
        lblEditImage.setMinimumSize(new java.awt.Dimension(85, 85));
        lblEditImage.setPreferredSize(new java.awt.Dimension(85, 85));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        editPanel.add(lblEditImage, gridBagConstraints);

        buttonsPanel.setMinimumSize(new java.awt.Dimension(455, 20));
        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDelete.setMaximumSize(new java.awt.Dimension(250, 50));
        btnDelete.setMinimumSize(new java.awt.Dimension(140, 50));
        btnDelete.setPreferredSize(new java.awt.Dimension(180, 50));
        btnDelete.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 5);
        buttonsPanel.add(btnDelete, gridBagConstraints);

        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdd.setMaximumSize(new java.awt.Dimension(250, 50));
        btnAdd.setMinimumSize(new java.awt.Dimension(140, 50));
        btnAdd.setPreferredSize(new java.awt.Dimension(180, 50));
        btnAdd.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 5);
        buttonsPanel.add(btnAdd, gridBagConstraints);

        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSave.setMaximumSize(new java.awt.Dimension(250, 50));
        btnSave.setMinimumSize(new java.awt.Dimension(140, 50));
        btnSave.setPreferredSize(new java.awt.Dimension(180, 50));
        btnSave.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 5);
        buttonsPanel.add(btnSave, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        editPanel.add(buttonsPanel, gridBagConstraints);

        centerPanel.add(editPanel, java.awt.BorderLayout.CENTER);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backButtonPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAnswer1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JComboBox<String> cboEditRole;
    private javax.swing.JComboBox<String> cboFilterRole;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel editPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel filtersPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEditBirthDate;
    private javax.swing.JLabel lblEditEmail;
    private javax.swing.JLabel lblEditId;
    private javax.swing.JLabel lblEditImage;
    private javax.swing.JLabel lblEditName;
    private javax.swing.JLabel lblEditPassword;
    private javax.swing.JLabel lblEditPasswordHint;
    private javax.swing.JLabel lblEditRole;
    private javax.swing.JLabel lblEditSecretAnswer;
    private javax.swing.JLabel lblEditSecretQuestion;
    private javax.swing.JLabel lblEditTitle;
    private javax.swing.JLabel lblFilterEmail;
    private javax.swing.JLabel lblFilterName;
    private javax.swing.JLabel lblFilterRole;
    private javax.swing.JLabel lblFiltersTitle;
    private javax.swing.JLabel lblResultsTitle;
    private javax.swing.JPanel searchResultsPanel;
    private javax.swing.JTextField txtEditBirthDate;
    private javax.swing.JTextField txtEditEmail;
    private javax.swing.JTextField txtEditId;
    private javax.swing.JTextField txtEditName;
    private javax.swing.JTextField txtEditPassword;
    private javax.swing.JTextField txtEditPasswordHint;
    private javax.swing.JTextField txtEditSecretAnswer;
    private javax.swing.JTextField txtEditSecretQuestion;
    private javax.swing.JTextField txtFilterEmail;
    private javax.swing.JTextField txtFilterName;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
}
