package com.quizmael.gui.helpers;

import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;

/**
 * Central panel manager using CardLayout to switch between different panels.
 *
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class PanelManager extends javax.swing.JPanel {

    // ------------------------------------------------------------
    //                      Attributes
    // ------------------------------------------------------------
    private CardLayout cardLayout;
    private Map<String, JPanel> panels;
    
    
    
    // ------------------------------------------------------------
    //                      Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form PanelManager
     */
    public PanelManager() {
        initComponents();
        
        cardLayout = new CardLayout(5, 5);
        setLayout(cardLayout);
        panels = new HashMap<>(); // To save the panels
    }

    /**
     * Adds a new panel to the manager with a given name.
     *
     * @param name  Unique name for the panel
     * @param panel The JPanel to add
     */
    public void addPanel(String name, JPanel panel) {
        panels.put(name, panel); // Saves on the map
        add(panel, name);        // Adds to the CardLayout with that key
    }

    /**
     * Shows the panel identified by the given name.
     *
     * @param name Name of the panel to show
     */
    public void showPanel(String name) {
        cardLayout.show(this, name); // Switch to the indicated panel
    }

    /**
     * Gets the panel previously registered with a given name.
     *
     * @param name The name of the panel
     * @return The JPanel instance
     */
    public JPanel getPanel(String name) {
        return panels.get(name);
    }
    
    // ------------------------------------------------------------
    //                      Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
