package com.quizmael.gui.windows;

import com.quizmael.gui.helpers.PanelManager;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 * Main application window that hosts the main content panel (PanelManager).
 *
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class MainWindow extends javax.swing.JFrame {

    // ------------------------------------------------------------
    //                      Attributes
    // ------------------------------------------------------------
    public static final Dimension minSize = new Dimension(1300, 1000);
    private final PanelManager panelManager;
    ImageIcon icon;
    
    // ------------------------------------------------------------
    //                      Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates the main window of the application.
     */
    public MainWindow() {
        initComponents();
        
        // Configures the main window
        setTitle("Quizmael");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setMinimumSize(minSize);
        setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        setLocationRelativeTo(null);   
        getContentPane().setLayout(new BorderLayout());
        icon = new ImageIcon(getClass().getResource("/icons/logo_32.png"));
        setIconImage(icon.getImage());
        
        
        // Adds PanelManager
        panelManager = new PanelManager();
        add(panelManager, BorderLayout.CENTER);
        
    }

    /**
     * Gets the panel manager that controls screen switching.
     * @return the PanelManager instance
     */    
    public PanelManager getPanelManager() {
        return panelManager;
    }
    
    
    // ------------------------------------------------------------
    //                      Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quizmael");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
