package com.quizmael.gui.windows;

import com.quizmael.gui.helpers.PanelManager;
import com.quizmael.util.LoggerUtil;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 * Main application window. Hosts the PanelManager and handles global window settings.
 *
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class MainWindow extends javax.swing.JFrame {

    // ------------------------------------------------------------
    //                      Attributes
    // ------------------------------------------------------------
    public static final Dimension MIN_SIZE = new Dimension(1300, 800);
    private final PanelManager panelManager;
    private ImageIcon icon;
    
    // ------------------------------------------------------------
    //                      Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates the main window of the application.
     */
    public MainWindow() {
        initComponents();
        setupWindow();
        
        // Adds PanelManager
        panelManager = new PanelManager();
        add(panelManager, BorderLayout.CENTER);
        LoggerUtil.info(getClass(), "Main Window initialized successfully.");
    }

    /**
     * Gets the panel manager that controls screen switching.
     * @return the PanelManager instance
     */    
    public PanelManager getPanelManager() {
        return panelManager;
    }
    
    // ------------------------------------------------------------
    //                      Private Methods
    // ------------------------------------------------------------

    private void setupWindow() {
        setTitle("Quizmael");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setMinimumSize(MIN_SIZE);
        // Using Toolkit to ensure it doesn't exceed screen bounds
        setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        setLocationRelativeTo(null);

        try {
            // Loading the icon from resources
            icon = new ImageIcon(getClass().getResource("/icons/logo_32.png"));
            setIconImage(icon.getImage());
        } catch (Exception e) {
            LoggerUtil.warn(getClass(), "Application icon not found.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quizmael");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
