package com.quizmael.gui.views.mainmenu;

import com.quizmael.controller.AppController;
import com.quizmael.model.User;
import com.quizmael.session.SessionContext;
import java.awt.Dimension;

/**
 * Main menu panel displayed after login.
 * Provides navigation to play quizzes, view results, or access settings.
 * 
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class MainMenuPanel extends com.quizmael.gui.common.BasePanel {
    
    // ------------------------------------------------------------
    //                     Attributes
    // ------------------------------------------------------------
    private final AppController appController;
    
    // ------------------------------------------------------------
    //                     Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form LoginPanel
     */
    public MainMenuPanel(AppController appController) {
        this.appController = appController;
        initComponents();
        
    }
    
    
    // ------------------------------------------------------------
    //                     Private Methods
    // ------------------------------------------------------------
    
    public void refreshUserName(String userName) {
        lblProfile.setText(userName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPane = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        btnAdminPanel = new javax.swing.JButton();
        westPane = new javax.swing.JPanel();
        centerPane = new javax.swing.JPanel();
        verticalGlue1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelBtnPlay = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        verticalGlue2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelBtnCreateQuiz = new javax.swing.JPanel();
        btnCreateQuiz = new javax.swing.JButton();
        verticalGlue3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelBtnAppOptions = new javax.swing.JPanel();
        btnAppOptions = new javax.swing.JButton();
        botVerticalGlue4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        eastPane = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        northPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 15, 0));
        northPane.setLayout(new java.awt.BorderLayout());

        lblProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user100.png"))); // NOI18N
        lblProfile.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProfile.setMaximumSize(new java.awt.Dimension(200, 200));
        lblProfile.setMinimumSize(new java.awt.Dimension(120, 120));
        lblProfile.setPreferredSize(new java.awt.Dimension(120, 120));
        lblProfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        northPane.add(lblProfile, java.awt.BorderLayout.EAST);

        btnAdminPanel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btnAdminPanel.setText("Administrar");
        btnAdminPanel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdminPanel.setMaximumSize(new java.awt.Dimension(400, 200));
        btnAdminPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        btnAdminPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        northPane.add(btnAdminPanel, java.awt.BorderLayout.WEST);

        add(northPane, java.awt.BorderLayout.NORTH);

        westPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 1, 1));
        westPane.setMinimumSize(new java.awt.Dimension(150, 600));
        westPane.setPreferredSize(new java.awt.Dimension(116, 116));
        westPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        add(westPane, java.awt.BorderLayout.WEST);

        centerPane.setMinimumSize(new java.awt.Dimension(600, 500));
        centerPane.setLayout(new javax.swing.BoxLayout(centerPane, javax.swing.BoxLayout.Y_AXIS));
        centerPane.add(verticalGlue1);

        panelBtnPlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnPlay.setMaximumSize(new java.awt.Dimension(400, 200));
        panelBtnPlay.setMinimumSize(new java.awt.Dimension(170, 120));
        panelBtnPlay.setPreferredSize(new java.awt.Dimension(170, 120));
        panelBtnPlay.setLayout(new java.awt.BorderLayout());

        btnPlay.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btnPlay.setText("Jugar test");
        btnPlay.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPlay.setMaximumSize(new java.awt.Dimension(400, 200));
        btnPlay.setMinimumSize(new java.awt.Dimension(170, 100));
        btnPlay.setPreferredSize(new java.awt.Dimension(170, 100));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        panelBtnPlay.add(btnPlay, java.awt.BorderLayout.CENTER);

        centerPane.add(panelBtnPlay);
        centerPane.add(verticalGlue2);

        panelBtnCreateQuiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnCreateQuiz.setMaximumSize(new java.awt.Dimension(400, 200));
        panelBtnCreateQuiz.setMinimumSize(new java.awt.Dimension(170, 120));
        panelBtnCreateQuiz.setPreferredSize(new java.awt.Dimension(170, 120));
        panelBtnCreateQuiz.setLayout(new java.awt.BorderLayout());

        btnCreateQuiz.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btnCreateQuiz.setText("Crear test");
        btnCreateQuiz.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCreateQuiz.setMaximumSize(new java.awt.Dimension(400, 200));
        btnCreateQuiz.setMinimumSize(new java.awt.Dimension(170, 100));
        btnCreateQuiz.setPreferredSize(new java.awt.Dimension(170, 100));
        panelBtnCreateQuiz.add(btnCreateQuiz, java.awt.BorderLayout.CENTER);

        centerPane.add(panelBtnCreateQuiz);
        centerPane.add(verticalGlue3);

        panelBtnAppOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnAppOptions.setMaximumSize(new java.awt.Dimension(400, 200));
        panelBtnAppOptions.setMinimumSize(new java.awt.Dimension(170, 120));
        panelBtnAppOptions.setPreferredSize(new java.awt.Dimension(170, 120));
        panelBtnAppOptions.setLayout(new java.awt.BorderLayout());

        btnAppOptions.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btnAppOptions.setText("Opciones");
        btnAppOptions.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAppOptions.setMaximumSize(new java.awt.Dimension(400, 200));
        btnAppOptions.setMinimumSize(new java.awt.Dimension(170, 100));
        btnAppOptions.setPreferredSize(new java.awt.Dimension(170, 100));
        panelBtnAppOptions.add(btnAppOptions, java.awt.BorderLayout.CENTER);

        centerPane.add(panelBtnAppOptions);
        centerPane.add(botVerticalGlue4);

        add(centerPane, java.awt.BorderLayout.CENTER);

        eastPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 1, 1));
        eastPane.setMinimumSize(new java.awt.Dimension(150, 600));
        eastPane.setPreferredSize(new java.awt.Dimension(116, 116));
        eastPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        add(eastPane, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        appController.getGameController().showQuizSelection();
    }//GEN-LAST:event_btnPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler botVerticalGlue4;
    private javax.swing.JButton btnAdminPanel;
    private javax.swing.JButton btnAppOptions;
    private javax.swing.JButton btnCreateQuiz;
    private javax.swing.JButton btnPlay;
    private javax.swing.JPanel centerPane;
    private javax.swing.JPanel eastPane;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JPanel northPane;
    private javax.swing.JPanel panelBtnAppOptions;
    private javax.swing.JPanel panelBtnCreateQuiz;
    private javax.swing.JPanel panelBtnPlay;
    private javax.swing.Box.Filler verticalGlue1;
    private javax.swing.Box.Filler verticalGlue2;
    private javax.swing.Box.Filler verticalGlue3;
    private javax.swing.JPanel westPane;
    // End of variables declaration//GEN-END:variables
}
