package com.quizmael.gui.views.mainmenu;

import com.quizmael.controller.AppController;
import com.quizmael.gui.common.*;
import com.quizmael.gui.views.auth.*;

/**
 * TODO: generar descripción
 * 
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class MainMenuPanel extends com.quizmael.gui.common.BasePanel {
    
    // ------------------------------------------------------------
    //                     Attributes
    // ------------------------------------------------------------

    
    // ------------------------------------------------------------
    //                     Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form LoginPanel
     */
    public MainMenuPanel(AppController controller) {
        initComponents();
    }
    
    
    // ------------------------------------------------------------
    //                     Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPane = new javax.swing.JPanel();
        btnAdminPanel = new javax.swing.JButton();
        btnProfileManagement = new javax.swing.JButton();
        westPane = new javax.swing.JPanel();
        centerPane = new javax.swing.JPanel();
        verticalGlue1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelBtnPlay = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        verticalGlue2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelBtnCreateQuiz = new javax.swing.JPanel();
        btnCreateQuiz = new javax.swing.JButton();
        verticalGlue3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelBtnAppOptions = new javax.swing.JPanel();
        btnAppOptions = new javax.swing.JButton();
        botVerticalGlue4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        eastPane = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        northPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 15, 0));
        northPane.setLayout(new java.awt.BorderLayout());

        btnAdminPanel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdminPanel.setMaximumSize(new java.awt.Dimension(400, 200));
        btnAdminPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        btnAdminPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        northPane.add(btnAdminPanel, java.awt.BorderLayout.WEST);

        btnProfileManagement.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnProfileManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProfileManagement.setMaximumSize(new java.awt.Dimension(200, 200));
        btnProfileManagement.setMinimumSize(new java.awt.Dimension(100, 100));
        btnProfileManagement.setPreferredSize(new java.awt.Dimension(100, 100));
        btnProfileManagement.setVerifyInputWhenFocusTarget(false);
        btnProfileManagement.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        northPane.add(btnProfileManagement, java.awt.BorderLayout.EAST);

        add(northPane, java.awt.BorderLayout.NORTH);

        westPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 1, 1));
        westPane.setMinimumSize(new java.awt.Dimension(150, 600));
        westPane.setPreferredSize(new java.awt.Dimension(116, 116));
        westPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        add(westPane, java.awt.BorderLayout.WEST);

        centerPane.setMinimumSize(new java.awt.Dimension(600, 500));
        centerPane.setLayout(new javax.swing.BoxLayout(centerPane, javax.swing.BoxLayout.Y_AXIS));
        centerPane.add(verticalGlue1);

        panelBtnPlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnPlay.setMaximumSize(new java.awt.Dimension(400, 200));
        panelBtnPlay.setMinimumSize(new java.awt.Dimension(170, 120));
        panelBtnPlay.setPreferredSize(new java.awt.Dimension(170, 120));
        panelBtnPlay.setLayout(new java.awt.BorderLayout());

        btnPlay.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPlay.setMaximumSize(new java.awt.Dimension(400, 200));
        btnPlay.setMinimumSize(new java.awt.Dimension(170, 100));
        btnPlay.setPreferredSize(new java.awt.Dimension(170, 100));
        panelBtnPlay.add(btnPlay, java.awt.BorderLayout.CENTER);

        centerPane.add(panelBtnPlay);
        centerPane.add(verticalGlue2);

        panelBtnCreateQuiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnCreateQuiz.setMaximumSize(new java.awt.Dimension(400, 200));
        panelBtnCreateQuiz.setMinimumSize(new java.awt.Dimension(170, 120));
        panelBtnCreateQuiz.setPreferredSize(new java.awt.Dimension(170, 120));
        panelBtnCreateQuiz.setLayout(new java.awt.BorderLayout());

        btnCreateQuiz.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCreateQuiz.setMaximumSize(new java.awt.Dimension(400, 200));
        btnCreateQuiz.setMinimumSize(new java.awt.Dimension(170, 100));
        btnCreateQuiz.setPreferredSize(new java.awt.Dimension(170, 100));
        panelBtnCreateQuiz.add(btnCreateQuiz, java.awt.BorderLayout.CENTER);

        centerPane.add(panelBtnCreateQuiz);
        centerPane.add(verticalGlue3);

        panelBtnAppOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnAppOptions.setMaximumSize(new java.awt.Dimension(400, 200));
        panelBtnAppOptions.setMinimumSize(new java.awt.Dimension(170, 120));
        panelBtnAppOptions.setPreferredSize(new java.awt.Dimension(170, 120));
        panelBtnAppOptions.setLayout(new java.awt.BorderLayout());

        btnAppOptions.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAppOptions.setMaximumSize(new java.awt.Dimension(400, 200));
        btnAppOptions.setMinimumSize(new java.awt.Dimension(170, 100));
        btnAppOptions.setPreferredSize(new java.awt.Dimension(170, 100));
        panelBtnAppOptions.add(btnAppOptions, java.awt.BorderLayout.CENTER);

        centerPane.add(panelBtnAppOptions);
        centerPane.add(botVerticalGlue4);

        add(centerPane, java.awt.BorderLayout.CENTER);

        eastPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 1, 1));
        eastPane.setMinimumSize(new java.awt.Dimension(150, 600));
        eastPane.setPreferredSize(new java.awt.Dimension(116, 116));
        eastPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        add(eastPane, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler botVerticalGlue4;
    private javax.swing.JButton btnAdminPanel;
    private javax.swing.JButton btnAppOptions;
    private javax.swing.JButton btnCreateQuiz;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnProfileManagement;
    private javax.swing.JPanel centerPane;
    private javax.swing.JPanel eastPane;
    private javax.swing.JPanel northPane;
    private javax.swing.JPanel panelBtnAppOptions;
    private javax.swing.JPanel panelBtnCreateQuiz;
    private javax.swing.JPanel panelBtnPlay;
    private javax.swing.Box.Filler verticalGlue1;
    private javax.swing.Box.Filler verticalGlue2;
    private javax.swing.Box.Filler verticalGlue3;
    private javax.swing.JPanel westPane;
    // End of variables declaration//GEN-END:variables
}
