package com.quizmael.gui.views.auth;

import com.quizmael.controller.AppController;

/**
 * Panel for user authentication via login form.
 * Allows users to log in with their credentials.
 * 
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class LoginPanel extends com.quizmael.gui.common.BasePanel {
    
    // ------------------------------------------------------------
    //                     Attributes
    // ------------------------------------------------------------
    private final AppController appController;
    
    // ------------------------------------------------------------
    //                     Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(AppController appController) {
        this.appController = appController;
        initComponents();
    }
    
    
    // ------------------------------------------------------------
    //                     Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        verticalGlue1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        verticalGlue4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        lblPassword = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        btnHint = new javax.swing.JButton();
        verticalGlue6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnForgottenPassword = new javax.swing.JButton();
        verticalGlue7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        chkKeepSessionOpen = new javax.swing.JCheckBox();
        verticalGlue8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnLogin = new javax.swing.JButton();
        verticalGlue9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnRegister = new javax.swing.JButton();
        verticalGlue2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnEnterGuest = new javax.swing.JButton();
        verticalGlue3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        northPanel = new javax.swing.JPanel();
        southPanel = new javax.swing.JPanel();
        eastPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.BorderLayout());

        centerPanel.setLayout(new javax.swing.BoxLayout(centerPanel, javax.swing.BoxLayout.Y_AXIS));
        centerPanel.add(verticalGlue1);

        lblUserName.setText("Nombre de usuario");
        lblUserName.setAlignmentX(0.5F);
        lblUserName.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        lblUserName.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName.setPreferredSize(new java.awt.Dimension(50, 30));
        centerPanel.add(lblUserName);

        txtUserName.setMaximumSize(new java.awt.Dimension(300, 40));
        txtUserName.setMinimumSize(new java.awt.Dimension(150, 25));
        txtUserName.setPreferredSize(new java.awt.Dimension(150, 25));
        centerPanel.add(txtUserName);
        centerPanel.add(verticalGlue4);

        lblPassword.setText("Contraseña");
        lblPassword.setAlignmentX(0.5F);
        lblPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        lblPassword.setMaximumSize(new java.awt.Dimension(300, 50));
        lblPassword.setMinimumSize(new java.awt.Dimension(50, 30));
        lblPassword.setPreferredSize(new java.awt.Dimension(50, 30));
        centerPanel.add(lblPassword);

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(50, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtPassword.setMinimumSize(new java.awt.Dimension(40, 22));
        txtPassword.setPreferredSize(new java.awt.Dimension(40, 22));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword);

        btnHint.setText("Pista");
        btnHint.setAlignmentX(0.5F);
        btnHint.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        btnHint.setMaximumSize(new java.awt.Dimension(50, 50));
        btnHint.setMinimumSize(new java.awt.Dimension(30, 30));
        btnHint.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(btnHint);

        centerPanel.add(jPanel1);
        centerPanel.add(verticalGlue6);

        btnForgottenPassword.setText("He olvidado mi contraseña");
        btnForgottenPassword.setAlignmentX(0.5F);
        btnForgottenPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        btnForgottenPassword.setMaximumSize(new java.awt.Dimension(200, 50));
        btnForgottenPassword.setMinimumSize(new java.awt.Dimension(80, 30));
        btnForgottenPassword.setPreferredSize(new java.awt.Dimension(80, 30));
        centerPanel.add(btnForgottenPassword);
        centerPanel.add(verticalGlue7);

        chkKeepSessionOpen.setText("Mantener la sesión abierta");
        chkKeepSessionOpen.setAlignmentX(0.5F);
        chkKeepSessionOpen.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        chkKeepSessionOpen.setMaximumSize(new java.awt.Dimension(300, 50));
        chkKeepSessionOpen.setMinimumSize(new java.awt.Dimension(50, 30));
        chkKeepSessionOpen.setPreferredSize(new java.awt.Dimension(50, 30));
        centerPanel.add(chkKeepSessionOpen);
        centerPanel.add(verticalGlue8);

        btnLogin.setText("Iniciar Sesión");
        btnLogin.setAlignmentX(0.5F);
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        btnLogin.setMaximumSize(new java.awt.Dimension(200, 50));
        btnLogin.setMinimumSize(new java.awt.Dimension(80, 30));
        btnLogin.setPreferredSize(new java.awt.Dimension(80, 30));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        centerPanel.add(btnLogin);
        centerPanel.add(verticalGlue9);

        btnRegister.setText("Registrarse");
        btnRegister.setAlignmentX(0.5F);
        btnRegister.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        btnRegister.setMaximumSize(new java.awt.Dimension(200, 50));
        btnRegister.setMinimumSize(new java.awt.Dimension(80, 30));
        btnRegister.setPreferredSize(new java.awt.Dimension(80, 30));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        centerPanel.add(btnRegister);
        centerPanel.add(verticalGlue2);

        btnEnterGuest.setText("Entrar como invitado");
        btnEnterGuest.setAlignmentX(0.5F);
        btnEnterGuest.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        btnEnterGuest.setMaximumSize(new java.awt.Dimension(200, 50));
        btnEnterGuest.setMinimumSize(new java.awt.Dimension(80, 30));
        btnEnterGuest.setPreferredSize(new java.awt.Dimension(80, 30));
        btnEnterGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterGuestActionPerformed(evt);
            }
        });
        centerPanel.add(btnEnterGuest);
        centerPanel.add(verticalGlue3);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout northPanelLayout = new javax.swing.GroupLayout(northPanel);
        northPanel.setLayout(northPanelLayout);
        northPanelLayout.setHorizontalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        northPanelLayout.setVerticalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(northPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout southPanelLayout = new javax.swing.GroupLayout(southPanel);
        southPanel.setLayout(southPanelLayout);
        southPanelLayout.setHorizontalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        southPanelLayout.setVerticalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(southPanel, java.awt.BorderLayout.PAGE_END);

        eastPanel.setMinimumSize(new java.awt.Dimension(400, 100));
        eastPanel.setPreferredSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        add(eastPanel, java.awt.BorderLayout.LINE_END);

        westPanel.setMinimumSize(new java.awt.Dimension(400, 100));

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        add(westPanel, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        appController.getAuthController().login(txtUserName.getText().trim(), txtPassword.getText().trim());
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        appController.showRegisterPanel();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnEnterGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterGuestActionPerformed
        appController.getAuthController().loginAsGuest();
    }//GEN-LAST:event_btnEnterGuestActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        btnLogin.doClick();
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterGuest;
    private javax.swing.JButton btnForgottenPassword;
    private javax.swing.JButton btnHint;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JCheckBox chkKeepSessionOpen;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel southPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.Box.Filler verticalGlue1;
    private javax.swing.Box.Filler verticalGlue2;
    private javax.swing.Box.Filler verticalGlue3;
    private javax.swing.Box.Filler verticalGlue4;
    private javax.swing.Box.Filler verticalGlue6;
    private javax.swing.Box.Filler verticalGlue7;
    private javax.swing.Box.Filler verticalGlue8;
    private javax.swing.Box.Filler verticalGlue9;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
}
