package com.quizmael.gui.views.auth;

/**
 * TODO: generar descripción
 * 
 * @author Ismael Reina Muñoz
 * @version 1.0
 */
public class RegisterPanel extends com.quizmael.gui.common.BasePanel {
    
    // ------------------------------------------------------------
    //                     Attributes
    // ------------------------------------------------------------

    
    // ------------------------------------------------------------
    //                     Public Methods
    // ------------------------------------------------------------
    
    /**
     * Creates new form LoginPanel
     */
    public RegisterPanel() {
        initComponents();
    }
    
    
    // ------------------------------------------------------------
    //                     Private Methods
    // ------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblPasswordRepeat = new javax.swing.JLabel();
        txtPasswordRepeat = new javax.swing.JTextField();
        lblPasswordHint = new javax.swing.JLabel();
        txtPasswordHint = new javax.swing.JTextField();
        lblSecretQuestion = new javax.swing.JLabel();
        txtSecretQuestion = new javax.swing.JTextField();
        lblSecretAnswer = new javax.swing.JLabel();
        txtSecretAnswer = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblBirthDate = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JTextField();
        lblProfilePicture = new javax.swing.JLabel();
        btnProfilePicture = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 35, 25, 35));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridBagLayout());

        lblUserName.setMaximumSize(new java.awt.Dimension(300, 50));
        lblUserName.setMinimumSize(new java.awt.Dimension(50, 30));
        lblUserName.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(lblUserName, gridBagConstraints);

        txtUserName.setMaximumSize(new java.awt.Dimension(300, 40));
        txtUserName.setMinimumSize(new java.awt.Dimension(150, 25));
        txtUserName.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(txtUserName, gridBagConstraints);

        lblPassword.setMaximumSize(new java.awt.Dimension(300, 50));
        lblPassword.setMinimumSize(new java.awt.Dimension(50, 30));
        lblPassword.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(lblPassword, gridBagConstraints);

        txtPassword.setMaximumSize(new java.awt.Dimension(300, 40));
        txtPassword.setMinimumSize(new java.awt.Dimension(150, 25));
        txtPassword.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(txtPassword, gridBagConstraints);

        lblPasswordRepeat.setMaximumSize(new java.awt.Dimension(300, 50));
        lblPasswordRepeat.setMinimumSize(new java.awt.Dimension(50, 30));
        lblPasswordRepeat.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(lblPasswordRepeat, gridBagConstraints);

        txtPasswordRepeat.setMaximumSize(new java.awt.Dimension(300, 40));
        txtPasswordRepeat.setMinimumSize(new java.awt.Dimension(150, 25));
        txtPasswordRepeat.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(txtPasswordRepeat, gridBagConstraints);

        lblPasswordHint.setMaximumSize(new java.awt.Dimension(300, 50));
        lblPasswordHint.setMinimumSize(new java.awt.Dimension(50, 30));
        lblPasswordHint.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(lblPasswordHint, gridBagConstraints);

        txtPasswordHint.setMaximumSize(new java.awt.Dimension(300, 40));
        txtPasswordHint.setMinimumSize(new java.awt.Dimension(150, 25));
        txtPasswordHint.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(txtPasswordHint, gridBagConstraints);

        lblSecretQuestion.setMaximumSize(new java.awt.Dimension(300, 50));
        lblSecretQuestion.setMinimumSize(new java.awt.Dimension(50, 30));
        lblSecretQuestion.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(lblSecretQuestion, gridBagConstraints);

        txtSecretQuestion.setMaximumSize(new java.awt.Dimension(300, 40));
        txtSecretQuestion.setMinimumSize(new java.awt.Dimension(150, 25));
        txtSecretQuestion.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(txtSecretQuestion, gridBagConstraints);

        lblSecretAnswer.setMaximumSize(new java.awt.Dimension(300, 50));
        lblSecretAnswer.setMinimumSize(new java.awt.Dimension(50, 30));
        lblSecretAnswer.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(lblSecretAnswer, gridBagConstraints);

        txtSecretAnswer.setMaximumSize(new java.awt.Dimension(300, 40));
        txtSecretAnswer.setMinimumSize(new java.awt.Dimension(150, 25));
        txtSecretAnswer.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(txtSecretAnswer, gridBagConstraints);

        lblEmail.setMaximumSize(new java.awt.Dimension(300, 50));
        lblEmail.setMinimumSize(new java.awt.Dimension(50, 30));
        lblEmail.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(lblEmail, gridBagConstraints);

        txtEmail.setMaximumSize(new java.awt.Dimension(300, 40));
        txtEmail.setMinimumSize(new java.awt.Dimension(150, 25));
        txtEmail.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 40);
        add(txtEmail, gridBagConstraints);

        lblBirthDate.setMaximumSize(new java.awt.Dimension(300, 50));
        lblBirthDate.setMinimumSize(new java.awt.Dimension(50, 30));
        lblBirthDate.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(lblBirthDate, gridBagConstraints);

        txtBirthDate.setMaximumSize(new java.awt.Dimension(300, 40));
        txtBirthDate.setMinimumSize(new java.awt.Dimension(150, 25));
        txtBirthDate.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(txtBirthDate, gridBagConstraints);

        lblProfilePicture.setMaximumSize(new java.awt.Dimension(300, 50));
        lblProfilePicture.setMinimumSize(new java.awt.Dimension(50, 30));
        lblProfilePicture.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(lblProfilePicture, gridBagConstraints);

        btnProfilePicture.setMaximumSize(new java.awt.Dimension(300, 40));
        btnProfilePicture.setMinimumSize(new java.awt.Dimension(150, 25));
        btnProfilePicture.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(btnProfilePicture, gridBagConstraints);

        btnRegister.setMaximumSize(new java.awt.Dimension(200, 50));
        btnRegister.setMinimumSize(new java.awt.Dimension(150, 25));
        btnRegister.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(btnRegister, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProfilePicture;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordHint;
    private javax.swing.JLabel lblPasswordRepeat;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JLabel lblSecretAnswer;
    private javax.swing.JLabel lblSecretQuestion;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordHint;
    private javax.swing.JTextField txtPasswordRepeat;
    private javax.swing.JTextField txtSecretAnswer;
    private javax.swing.JTextField txtSecretQuestion;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
